import { useState } from 'react'
import { Container } from "@components/container";
import { Header } from "@components/header";
import { CartDetails } from '@components/cartinfo/summary';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, Input } from '@chakra-ui/react';
import { navigate } from 'vite-plugin-ssr/client/router';


type Props = {
    setUserInfo: Function,
}

export const NonLoggedUser = ({ setUserInfo }: Props) => {
    const [fullName, setFullName] = useState('');
    const [phone, SetPhone] = useState('');
    const [message, setMessage] = useState("");
    
    const onProceed = () => {
        if (phone !== '') {
            setUserInfo({
                full_name: fullName,
                phone: phone
            })
            navigate('/cart/paymentmethod');
        } else {
            setMessage("Please Enter Your Mobile Number");
        }
    }

    return (
        <div>
            <Container>
                <Header />
                <div className="px-20 sm:px-2 sm:hidden">
                    <div className="h-4"></div>
                    <Breadcrumb className="font-normal text-lg list-none text-breadcrumbs">
                        <BreadcrumbItem>
                            <BreadcrumbLink href='/'>Home</BreadcrumbLink>
                        </BreadcrumbItem>
                        <BreadcrumbItem>
                            <BreadcrumbLink href='/cart'>Cart</BreadcrumbLink>
                        </BreadcrumbItem>
                        <BreadcrumbItem className='select-none font-normal text-ellipsis text-left break-words line-clamp-1' isCurrentPage>
                            <BreadcrumbLink href={`/cart/nonloggeduser`}>Enter Details </BreadcrumbLink>
                            <ol className="p-0 list-none"></ol>
                        </BreadcrumbItem>
                    </Breadcrumb>
                </div>
                <div className="h-4"></div>
                <div><h1 className="font-bold text-xl text-custom_black font-manrope px-20 sm:px-4 sm:text-base">Enter Details</h1></div>
                <p className="hidden sm:block text-base sm:text-xs text-breadcrumbs py-2 px-4">This information will be shown on the bill and for SMS.</p>
                <div className="h-4"></div>
                <div className="flex flex-row sm:grow h-full justify-between gap-4 sm:flex-col px-20 sm:px-4">
                    <div className="flex flex-col justify-center gap-4 w-full bg-neutral-50 rounded-lg p-4 sm:bg-neutral-100 sm:px-0">
                        <div className='flex flex-col gap-2'>
                            <label htmlFor="mobilenumber" className="text-lg text-custom_black sm:text-sm">Mobile Number</label>
                            <Input className='bg-neutral-100 rounded p-2 w-1/3 sm:w-full sm:bg-neutral-50'
                                maxLength={10}
                                onChange={(e) => {
                                    const phoneRegex = /^[0-9]{10}$/
                                    const phone = e.target.value
                                    if (phoneRegex.test(phone)) {
                                        SetPhone(phone)
                                        setMessage("")
                                    } else {
                                        setMessage("Please Enter valid phone number.")
                                    }
                                }
                                } />
                        </div>
                        <div className='flex flex-col gap-2'>
                            <label htmlFor="Name" className="text-lg text-custom_black sm:text-sm">Name</label>
                            <Input className='bg-neutral-100 rounded p-2 w-1/3 sm:w-full sm:bg-neutral-50' onChange={(e) => setFullName(e.target.value)} />
                        </div>
                        <div className="col-span-6 py-2">
                            <p className="text-error-900 font-semibold text-center">{message}</p>
                        </div>
                        <p className="text-base text-breadcrumbs pt-2 sm:hidden">This information will be used on the bill generated by the transaction and it will be sent to the mobile number through SMS.</p>
                    </div>
                    <CartDetails actionFun={onProceed} btnName="PROCEED" isHidden={true} />
                </div>
            </Container>
        </div>
    )
}